# File Name: asymmetric_network_serializer.py
# Location: /src/network_layer/
# Subsystem: Dual-Channel Asymmetric Actuator Serial Output Serializer

import math
from typing import Dict, Any, Tuple

class AsymmetricNetworkSerializer:
    def __init__(self, prefix_manufacturer: str = "PUNVC"):
        """
        Initializes the dual-channel asynchronous serial output protocol engine.
        prefix_manufacturer: 5-character proprietary identifier string layer.
        """
        self.base_prefix = prefix_manufacturer.upper()[:5]
        self.port_header = f"{self.base_prefix}PRT"
        self.stbd_header = f"{self.base_prefix}STB"

    def _compute_nmea_checksum(self, payload: str) -> str:
        """Calculates a standard industrial 8-bit XOR hexadecimal validation byte."""
        checksum = 0
        for char in payload:
            checksum ^= ord(char)
        return f"{checksum:02X}"

    def serialize_asymmetric_actuator_channels(self, stabilizer_matrix_output: Dict[str, Any], depth_slew_cap: float = 15.0) -> Tuple[bytes, bytes]:
        """
        Ingests the calculations generated by the Asymmetric Roll Stabilization Matrix, 
        formats the independent port/starboard blocks, and outputs dual binary ASCII streams.
        """
        port_angle = stabilizer_matrix_output.get('command_port_actuator_deg', 0.0)
        stbd_angle = stabilizer_matrix_output.get('command_stbd_actuator_deg', 0.0)
        tracking_mode = stabilizer_matrix_output.get('stabilization_state', 'NOMINAL_STORM_DAMPING')
        
        # Isolate combat lock gating parameters to trigger fast-acting hydraulic valve states
        combat_lock_bit = 1 if tracking_mode == "APEX_COMBAT_LOCK_ACTIVE" else 0

        # 1. COMPILE PORT CHANNEL SENTENCE FRAME ($PUNVCPRT)
        port_payload = f"{self.port_header},{port_angle:.2f},{depth_slew_cap:.1f},{combat_lock_bit}"
        port_cs = self._compute_nmea_checksum(port_payload)
        port_sentence = f"${port_payload}*{port_cs}\r\n"

        # 2. COMPILE STARBOARD CHANNEL SENTENCE FRAME ($PUNVCSTB)
        stbd_payload = f"{self.stbd_header},{stbd_angle:.2f},{depth_slew_cap:.1f},{combat_lock_bit}"
        stbd_cs = self._compute_nmea_checksum(stbd_payload)
        stbd_sentence = f"${stbd_payload}*{stbd_cs}\r\n"

        # Convert directly to strict standard 8-bit ASCII bytes to bypass python encoding latencies
        return port_sentence.encode('ascii'), stbd_sentence.encode('ascii')

# Verification and Integration Loop Test Profile
if __name__ == "__main__":
    serializer = AsymmetricNetworkSerializer(prefix_manufacturer="PUNVC")
    
    # Mock data snapshot mimicking an active heavy-storm firing calculation matrix step
    mock_stabilizer_output = {
        "command_port_actuator_deg": -18.45,
        "command_stbd_actuator_deg": 14.12,
        "firing_interlock_cleared": True,
        "stabilization_state": "APEX_COMBAT_LOCK_ACTIVE",
        "asymmetric_split_delta_deg": 32.57
    }
    
    print("DUAL-CHANNEL RS-422 BUS WIRE OUTPUT ENCODER:")
    print("=" * 72)
    
    binary_port_frame, binary_stbd_frame = serializer.serialize_asymmetric_actuator_channels(
        stabilizer_matrix_output=mock_stabilizer_output,
        depth_slew_cap=12.5 # Slower slew cap example for shallow water or rough storms
    )
    
    print("Port Actuator Wire Packet String:")
    print(binary_port_frame.decode('ascii').strip())
    print("\nStarboard Actuator Wire Packet String:")
    print(binary_stbd_frame.decode('ascii').strip())
