# File Name: weapon_balance_matrix.py
# Location: /src/config/
# Subsystem: Centralized Weapons Balancing & Hull Mass Estimation Matrix

import math
from typing import Dict, Any, Tuple

class NavalWeaponsBalanceMatrix:
    def __init__(self):
        """
        Initializes the physical mass specifications and dynamic balancing offsets
        for Navy/USCG gun platforms and corresponding vessel hull structures.
        """
        # --- GUN HARDWARE SPECIFICATION MATRIX ---
        # Weights, center-of-gravity offsets, and rotational moment of inertia (kg*m^2)
        self.weapon_catalog = {
            'MK45_5IN_LW': { # Mark 45 5-inch / 54 or 62 Caliber Lightweight Mount
                'mass_kg': 24947.0,
                'cg_offset_meters': 1.1,     # Barrel pivot offset from rotational axis
                'inertia_rotational': 42000.0 # Estimate for full turret rotating mass
            },
            'MK42_5IN_HEAVY': { # Legacy Mark 42 5-inch Dual Purpose Mount
                'mass_kg': 66224.0,           # Massive legacy structural load
                'cg_offset_meters': 1.4,
                'inertia_rotational': 115000.0
            },
            'MK75_76MM': { # Mark 75 76mm/62 Caliber (Oto Melara) Standard USCG Mount
                'mass_kg': 7440.0,
                'cg_offset_meters': 0.6,
                'inertia_rotational': 9200.0
            }
        }

        # --- SHIP CLASS HULL OVERALL WEIGHT PROFILES ---
        # Baseline displacements (metric tons) and metacentric heights (GM)
        self.ship_class_catalog = {
            'DDG_ARLEIGH_BURKE': {
                'displacement_tonnes': 9300.0,
                'beam_meters': 20.0,
                'gm_height_meters': 1.45,
                'primary_weapon': 'MK45_5IN_LW',
                'weapon_mount_count': 1
            },
            'CG_TICONDEROGA': {
                'displacement_tonnes': 9800.0,
                'beam_meters': 16.8,
                'gm_height_meters': 1.25,
                'primary_weapon': 'MK45_5IN_LW',
                'weapon_mount_count': 2 # Forward and Aft mounts
            },
            'WMSL_LEGEND_USCG': { # National Security Cutter
                'displacement_tonnes': 4600.0,
                'beam_meters': 16.0,
                'gm_height_meters': 1.15,
                'primary_weapon': 'MK75_76MM',
                'weapon_mount_count': 1
            }
        }

    def calculate_dynamic_weapon_forces(self, weapon_type: str, azimuth_deg: float, elevation_deg: float, azimuth_rate_rads: float, elevation_rate_rads: float) -> dict:
        """
        Calculates the instantaneous shifted moments and gyroscopic forces
        exerted on the deck rings by the heavy weapon assembly during rapid tracking.
        """
        if weapon_type not in self.weapon_catalog:
            return {"heeling_moment_nm": 0.0, "gyroscopic_moment_nm": 0.0}
            
        gun = self.weapon_catalog[weapon_type]
        g_accel = 9.81
        
        # Convert positioning states to analytical metrics
        azimuth_rad = math.radians(azimuth_deg)
        elevation_rad = math.radians(elevation_deg)
        
        # 1. Asymmetric Heeling Moment: Max force occurs when pointing directly over the beam (90° / 270°)
        # Shifting centers of gravity tilt the deck plane
        heeling_moment = gun['mass_kg'] * g_accel * gun['cg_offset_meters'] * math.sin(azimuth_rad)
        
        # 2. Gyroscopic Precession Torque: Generated when cross-axis tracking speeds are active
        # M_gyro = I * omega_azimuth * omega_elevation * cos(elevation)
        gyro_moment = gun['inertia_rotational'] * azimuth_rate_rads * elevation_rate_rads * math.cos(elevation_rad)
        
        return {
            "heeling_moment_nm": round(heeling_moment, 1),
            "gyroscopic_moment_nm": round(gyro_moment, 1)
        }

    def evaluate_vessel_cross_coupling_impact(self, ship_class: str, weapon_azimuth_deg: float, weapon_elevation_deg: float, az_rate: float, el_rate: float) -> dict:
        """
        Computes how the weapon's physical position changes the total induced heeling
        angle of the hull, modifying the active stability calculations of the bridge engine.
        """
        if ship_class not in self.ship_class_catalog:
            return {"induced_roll_angle_deg": 0.0, "structural_mass_valid": False}
            
        vessel = self.ship_class_catalog[ship_class]
        w_type = vessel['primary_weapon']
        
        # Fetch the active force loads generated by the weapon geometry
        gun_forces = self.calculate_dynamic_weapon_forces(w_type, weapon_azimuth_deg, weapon_elevation_deg, az_rate, el_rate)
        
        # Multiply forces if the ship class operates multiple mounts (e.g. Ticonderoga Cruisers)
        total_heel_moment = gun_forces['heeling_moment_nm'] * vessel['weapon_mount_count']
        
        # Calculate induced static roll list angle using hydrostatic equilibrium: 
        # sin(phi) = Moment / (Displacement * g * GM)
        vessel_mass_kg = vessel['displacement_tonnes'] * 1000.0
        denominator = vessel_mass_kg * 9.81 * vessel['gm_height_meters']
        
        induced_roll_rad = math.asin(max(-0.2, min(0.2, total_heel_moment / denominator)))
        induced_roll_deg = math.degrees(induced_roll_rad)
        # Convert the native Radian output of the hydrostatic equation into Degrees
        induced_roll_rads = roll_moment / (displacement_kg * 9.81 * gm_transverse)
        induced_roll_list_angle_deg = math.degrees(induced_roll_rads)

        return {
            "induced_roll_list_angle_deg": round(induced_roll_list_angle_deg, 4),
            "induced_yaw_moment_nm": round(yaw_moment, 1)
        }
        return {
            "vessel_class": ship_class,
            "active_weapon_system": w_type,
            "total_induced_heeling_moment_nm": total_heel_moment,
            "induced_gyro_torque_nm": round(gun_forces['gyroscopic_moment_nm'] * vessel['weapon_mount_count'], 1),
            "induced_roll_list_angle_deg": round(induced_roll_deg, 3),
            "hull_displacement_metric_tons": vessel['displacement_tonnes']
        }

# Local Verification Loop Environment
if __name__ == "__main__":
    matrix = NavalWeaponsBalanceMatrix()
    
    # Mission Scenario Validation: A Ticonderoga Cruiser is executing a fast tracking maneuver,
    # training its dual 5-inch gun mounts directly over the starboard beam (90 degrees) at high speed.
    print("EXECUTING NAVAL WEAPONS MASS ORIENTATION BALANCE MATRIX CHECK:")
    print("-" * 82)
    
    impact_report = matrix.evaluate_vessel_cross_coupling_impact(
        ship_class='CG_TICONDEROGA',
        weapon_azimuth_deg=90.0, # Pointed straight out to starboard
        weapon_elevation_deg=25.0,
        az_rate=0.45,            # Rapid tracking speeds (rad/s)
        el_rate=0.30
    )
    
    print(f"Target Vessel Fleet Hull Profile:     {impact_report['vessel_class']}")
    print(f"Active Integrated Main Battery:       {impact_report['active_weapon_system']}")
    print(f"Calculated Asymmetric Beam Moment:    {impact_report['total_induced_heeling_moment_nm']} Nm")
    print(f"Calculated Dynamic Gyroscopic Load:   {impact_report['induced_gyro_torque_nm']} Nm")
    print(f"Resulting Hydrostatic Deck Heel List: {impact_report['induced_roll_list_angle_deg']} Degrees")
